M48
; DRILL file {KiCad 8.0.5} date 2025-01-04T02:07:15+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-04T02:07:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X3.7819Y-3.2087
X3.9819Y-3.2087
T2
X3.8331Y-2.7441
X3.9331Y-2.7441
T3
X3.4961Y-2.8961
X3.4961Y-2.9961
M30
